name: "Build Android"

on: workflow_dispatch

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-build
          path: build/app/outputs/apk/release/app-release.apk
      - run: flutter build appbundle
      - name: Archive App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: appbundle-build
          path: build/app/outputs/bundle/release/app-release.aab
