name: "Build and Release Android"

on:
  push:
    tags:
      - "v*" # Trigger on new tags like v1.0.0, v2.3.1 etc
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-build
          path: build/app/outputs/apk/release/app-release.apk
      - run: flutter build appbundle
      - name: Archive App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: appbundle-build
          path: build/app/outputs/bundle/release/app-release.aab

  release:
    name: Create Release
    needs: build # this job must come after the build job
    runs-on: ubuntu-latest
    permissions:
        contents: write # give permissions to create release
    if: startsWith(github.ref, 'refs/tags/') # Only run on tags
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: apk-build
          path: apk
      - name: Download App Bundle Artifact
        uses: actions/download-artifact@v3

        with:
          name: appbundle-build
          path: appbundle
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release created from tag ${{ github.ref }}
            This release includes an APK and an App Bundle.
          draft: false
          prerelease: false
      - name: Upload APK Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Upload App Bundle Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./appbundle/app-release.aab
          asset_name: app-release.aab
          asset_content_type: application/octet-stream
